# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12.0"
  config.vm.synced_folder ".", "/vagrant"
  remote_server_one = "one"
  remote_server_two = "two"
  remote_server_three = "three"

  config.vm.define remote_server_one do |s|
    s.vm.hostname = remote_server_one
    s.vm.network 'private_network', ip: '192.168.56.110'
    s.vm.provision "shell", path: "./init-ssh.sh"
    s.vm.provider "virtualbox" do |vb|
  	  vb.cpus = 1
      vb.memory = "1024"
      vb.name = remote_server_one
    end
  end


  config.vm.define remote_server_two do |s|
    s.vm.hostname = remote_server_two
    s.vm.network 'private_network', ip: '192.168.56.111'
    s.vm.provision "shell", path: "./init-ssh.sh"
    s.vm.provider "virtualbox" do |vb|
  	  vb.cpus = 1
      vb.memory = "1024"
      vb.name = remote_server_two
    end
  end

  config.vm.define remote_server_three do |s|
    s.vm.hostname = remote_server_three
    s.vm.network 'private_network', ip: '192.168.56.112'
    s.vm.provision "shell", path: "./init-ssh.sh"
    s.vm.provider "virtualbox" do |vb|
  	  vb.cpus = 1
      vb.memory = "1024"
      vb.name = remote_server_three
    end
  end


end