---
- name: Deploy WordPress with Ansible
  hosts: yismaili-host
  gather_facts: no
  become: yes

  tasks:
    - name: Copy src directory to /home
      copy:
        src: /home/yoyo/Desktop/cloud_1/src
        dest: /home/
    
    - name: Create directories for MariaDB and WordPress
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /home/data/mariadb
        - /home/data/wordpress
    
    - name: Pull Docker registry image
      docker_image:
        name: registry
        tag: latest
        source: pull
    
    - name: Run Docker registry container
      docker_container:
        name: my_registry
        image: registry:latest
        state: started
        ports:
          - "{{ docker_registry_port }}"
    
    - name: Wait for Docker registry to be up and running
      uri:
        url: "{{ docker_registry_url }}"
        return_content: yes
      register: result
    
    - name: Check if Docker registry is running
      debug:
        msg: "Docker registry is up and running"
      when: result.status == 200
    
    - name: Build and push MariaDB Docker image
      docker_image:
        build:
          path: "{{ image_build_path_mariadb }}"
        name: "localhost:5000/{{ image_mariadb }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build
    
    - name: Build and push WordPress Docker image
      docker_image:
        build:
          path: "{{ image_build_path_wordpress }}"
        name: "localhost:5000/{{ image_wordpress }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build
    
    - name: Build and push Nginx Docker image
      docker_image:
        build:
          path: "{{ image_build_path_nginx }}"
        name: "localhost:5000/{{ image_nginx }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build
    
    - name: Run Docker Compose for building images and running containers
      become: yes
      command: docker compose up -d --build
      args:
        chdir: "{{ docker_compose_path }}"