version: "3" 
# Run containers 
services: 
  mariadb:
      container_name: mariadb
      env_file:
        - .env
      ports:
        - 3360:3306
      # build: ./requirements/mariadb
      image: localhost:5000/mariadb:inceotion
      restart: always
      volumes:
        - db:/var/lib/mysql
      networks:
        - appnwrk

  wordpress:
      container_name: wordpress
      env_file:
        - .env
      depends_on:
        - mariadb
      # build: ./requirements/wordpress
      image: localhost:5000/wordpress:inceotion
      restart: always
      ports:
        - 9000:9000
      volumes:
        - wp:/var/www/html
      networks:
        - appnwrk

  nginx:
      container_name: nginx
      env_file:
        - .env
      # build: ./requirements/nginx
      image: localhost:5000/nginx:inceotion
      depends_on:
        - wordpress
      restart: always
      ports: 
       - 443:443
      volumes:
        - wp:/var/www/html
      networks:
        - appnwrk

# Volumes for storing data 
volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yismaili/data/mariadb
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yismaili/data/wordpress

# Network configuration
networks:
  appnwrk:
    driver: bridge
