---
- name: Pull Docker registry image
  docker_image:
    name: registry
    tag: latest
    source: pull

- name: Run Docker registry container
  docker_container:
    name: my_registry
    image: registry:latest
    state: started
    ports:
      - "{{ docker_registry_port }}"

- name: Wait for Docker registry to be up and running
  wait_for:
    host: localhost
    port: "{{ docker_registry_port.split(':')[0] }}"
    delay: 5
    timeout: 30

- name: Check if Docker registry is running
  debug:
    msg: "Docker registry is up and running"
